version: '2.0'
services:
  webserver:
    image: nginx:latest
    container_name: webserver
    ports:
     - 8090:80
    networks:
     - acardenasc-network

  springboot-backend:
    image: alancardenas/ms-backend:v1
    ports:
     - 8080:8080
    networks:
     - acardenasc-network

  angular:
    image: novocompliancetemp/angular:latest
    ports:
     - 8070:8080
    networks:
     - acardenasc-network

#Docker Networks
networks:
  acardenasc-network:
    driver: bridge
